### ISSUE TITLE
Add staged commit discussion to developer guide

### ISSUE THREAD

**Issue by morazow** [exasol/spark-connector#162]
### Situation

We had [short discussion](https://github.com/exasol/spark-connector/pull/161/files#r1204096803) on Spark job's staged commit behavior. It would be helpful to document these discussion in the developer guide.

Also add UUID applicationID (https://github.com/exasol/spark-connector/pull/161#discussion_r1204180748) description to developer guide.

```[tasklist]
### Tasks
- [x] Document how intermediate folder created using UUIDs
- [x] Document staged commit behaviour
- [x] Document why we use `1000` for file as limit
```

### Acceptance Criteria

- Updated developer guide with review discussions
